layout(local_size_x = 64) in;
layout(r32ui, binding = 0) uniform readonly uimage3D u_Src;
layout(std430, binding = 1) buffer histoLayout
{
    uint u_Dst[64];
};

void main()
{
    int z = int(gl_GlobalInvocationID.x);
    uint val = 0;

    val += imageLoad(u_Src, ivec3(0, 0, z)).r;
    val += imageLoad(u_Src, ivec3(0, 1, z)).r;
    val += imageLoad(u_Src, ivec3(1, 0, z)).r;
    val += imageLoad(u_Src, ivec3(1, 1, z)).r;

    u_Dst[z] = val;
}
