#version 430

layout(local_size_x = 16, local_size_y = 16) in;
layout(rgba16f, binding = 0) uniform readonly image2D u_Src;
layout(r32ui, binding = 1) uniform uimage1D u_Histogram;

void main()
{
    vec3 color = imageLoad(u_Src, ivec2(gl_GlobalInvocationID.xy)).rgb;
    float fbin = clamp(35.16096947 * log(1.0 + dot(color, vec3(0.2126, 0.7152, 0.0722))), 0.0, 63.0);

    imageAtomicAdd(u_Histogram, int(fbin), uint(1));
}
